### ISSUE TITLE
session not created: This version of ChromeDriver only supports Chrome version 75

### ISSUE THREAD

**Issue by sherzberg** [bonigarcia/webdrivermanager#342]
I started getting this error sometime recently in my own code base, but I also just checked out master (d1e626bb180b012e5c2ec88da9c88e1286114c09) and I get the same thing when running the io.github.bonigarcia.wdm.test.ChromeTest test from this repository.

As you can see from the log, the Downloader gets chrome `75.0.3770.8` and sets up my environment to use that downloaded driver, but I still get the error `session not created: This version of ChromeDriver only supports Chrome version 75`.

Am I missing something?

```
2019-05-16 08:42:01 [main] DEBUG io.github.bonigarcia.wdm.Shell.runAndWaitNoLog(70) -- There was a problem executing command <google-chrome --version> on the shell: Cannot run program "google-chrome" (in directory "."): error=2, No such file or directory
2019-05-16 08:42:01 [main] DEBUG i.g.bonigarcia.wdm.WebDriverManager.detectDriverVersionFromBrowser(573) -- The proper chromedriver version for your Google Chrome is unknown ... trying with the latest
2019-05-16 08:42:01 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.getDriversFromXml(1006) -- Reading https://chromedriver.storage.googleapis.com/ to seek chromedriver
2019-05-16 08:42:01 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.checkLatest(909) -- Latest version of chromedriver is 75.0.3770.8
2019-05-16 08:42:01 [main] INFO  io.github.bonigarcia.wdm.Downloader.downloadAndExtract(128) -- Downloading https://chromedriver.storage.googleapis.com/75.0.3770.8/chromedriver_linux64.zip
2019-05-16 08:42:02 [main] INFO  io.github.bonigarcia.wdm.Downloader.extract(183) -- Extracting binary from compressed file chromedriver_linux64.zip
2019-05-16 08:42:02 [main] INFO  i.g.bonigarcia.wdm.WebDriverManager.exportDriver(1042) -- Exporting webdriver.chrome.driver as /home/sherzberg/.m2/repository/webdriver/chromedriver/linux64/75.0.3770.8/chromedriver
Starting ChromeDriver 75.0.3770.8 (681f24ea911fe754973dda2fdc6d2a2e159dd300-refs/branch-heads/3770@{#40}) on port 28781
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.

org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 75
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'tiblets', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.113-1-MANJARO', java.version: '1.8.0_212'
Driver info: driver.version: ChromeDriver
remote stacktrace: #0 0x56542eb82299 <unknown>


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at io.github.bonigarcia.wdm.test.ChromeTest.setupTest(ChromeTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255
```

**Comment by bonigarcia** [comment]
It seems WebDriverManager is not able to determine the version of your browser, in this case, Chrome. I am working in a new version to solve this issue.

**Comment by sherzberg** [comment]
Great, thanks for the quick reply. If you have an idea of where the issue is, I would be glad to take a look at trying to fix it.

**Comment by n0y004v** [comment]
Iam facing this issue as well in my windows machine ,and I can not update my chrome browser .It is managed by my organization.What is the work around ?
I tried adding capabilities but it is not working

**Comment by bonigarcia** [comment]
This should be fixed in version 3.6.0, recently released.

**Comment by sherzberg** [comment]
Excellent! version 3.6.0 does fix my original issue in our codebase. Thanks!

**Comment by n0y004v** [comment]
> This should be fixed in version 3.6.0, recently released.

Are you talking about selenium version ??

**Comment by bonigarcia** [comment]
> Are you talking about selenium version ??

WebDriverManager 3.6.0.

**Comment by n0y004v** [comment]
Issue is not fixed even with 3.6.0

session not created: This version of ChromeDriver only supports Chrome version 75
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'

**Comment by Snipx** [comment]
The fix does not work for me either. Which information can I provide to help @bonigarcia ?

**Comment by hasanqusay** [comment]
I have the same issue

**Comment by selfrefactor** [comment]
This prevents out of the box `e2e` testing with latest `Angular` version. I hope there is some progress with this.

**Comment by Hafuma** [comment]
Hey all. Any update on this issue? O maybe someone knows a reliable workaround?

**Comment by gauravpatel2016** [comment]
This just happened to us.

 testImplementation "org.seleniumhq.selenium:selenium-api:3.141.59"
  testImplementation "org.seleniumhq.selenium:selenium-chrome-driver:3.141.59"
  testImplementation "org.seleniumhq.selenium:selenium-firefox-driver:3.141.59"
  testImplementation "org.seleniumhq.selenium:selenium-ie-driver:3.141.59"
  testImplementation "org.seleniumhq.selenium:selenium-java:3.141.59"
  testImplementation "org.seleniumhq.selenium:selenium-remote-driver:3.141.59"
  testImplementation "org.seleniumhq.selenium:selenium-safari-driver:3.141.59"
  testImplementation "org.seleniumhq.selenium:selenium-support:3.141.59"
  testImplementation "com.codeborne:selenide:5.3.1"
  testImplementation "org.hamcrest:hamcrest:2.1"
  **testImplementation "io.github.bonigarcia:webdrivermanager:3.7.1"**
  testImplementation "org.testng:testng:6.14.3"

**Comment by AmanKum** [comment]
I am facing the same issue, i have also tried to download relevant chromedriver.exe file which supports my chrome version and provided it's path to "path" environement variable, But this also didnt worked for me.

**Comment by AmanKum** [comment]
I have also tried to put WebDriverManager 3.6.0, dependency in pom file of my maven project, but still getting the same error with chrome only. However, Firefox is working as expected.

**Comment by AmanKum** [comment]
![image](https://user-images.githubusercontent.com/55732257/65599835-5ede8d80-dfbc-11e9-9c55-919facabd067.png)
This worked for me, but this doesn't seem to be a permanent solution.

**Comment by ArvindRed** [comment]
I am having the same issue 
`[chrome #01-0] SessionNotCreatedError: session not created: This version of ChromeDriver only supports Chrome version 75`

My chromedriver version installed by webdriver manager 12.1.7 was 77.0.3865.40, I have downgraded the chromedriver version to 75.0.3770.140 but still, I see the above-mentioned error while running the code.

`webdriver-manager status 
webdriver-manager: using global installed version 12.1.7
[10:44:37] I/status - selenium standalone version available: 3.141.59 [last]
[10:44:37] I/status - chromedriver versions available: 75.0.3770.140 [last], 75.0.3770.80, 77.0.3865.40
[10:44:37] I/status - geckodriver version available: v0.25.0 [last]
[10:44:37] I/status - IEDriverServer is not present
[10:44:37] I/status - android-sdk is not present
[10:44:37] I/status - appium is not present`

**Comment by mecanda12** [comment]
I have same issue "SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 75". 

I used robot framework and latest selenium version 4.0.0. 

I tried several version of chrome driver non of them work.  current browser version 77.0.3865.90
and driver 77.0.3865.40

**Comment by blodgettza** [comment]
I'm getting this issue as well:

```
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class
org.openqa.selenium.chrome.ChromeDriver (session not created: This version of ChromeDriver only supports Chrome version 75
```

**Comment by rodor87** [comment]
Same issue here for me.
I am using webdrivermanager 3.7.1 and chrome 77. It seems that when  `ChromeDriverManager.chromedriver().setup()` is used, then chromedriver 78 gets downloaded, which throws error 
`Caused by: org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 78
`

**Comment by amirated** [comment]
I got this working. Here are the steps:

I was getting this error:
`selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 75`

I went to `chrome://settings/help` in my Google Chrome and found the version to be:
`Version 77.0.3865.90 (Official Build) (64-bit)`

Then I went to: https://sites.google.com/a/chromium.org/chromedriver/downloads
and downloaded the version for 77.
Set the path of chromedriver in my code to the new downloaded chromedriver and it worked.

**Comment by bonigarcia** [comment]
Everyone in this post, please take into account this a closed issue. If there is still a problem with the latest version of WebDriverManager (3.7.1 at the time of this writing), please open a new issue about it. In that new issue, please fill **all the fields** supplied in the template (description of the problem, browser and version, operating system, etc). It is of paramount importance to provide also the **WebDriverManager traces** in the new issue. Otherwise, I will not be able to determine the root of the problem. For those traces, I strongly recommend using the `DEBUG` level for the `io.github.bonigarcia` package. In addition, it would interesting to clean the preferences values before collecting the reported traces, e.g.:

```
WebDriverManager.chromedriver().clearPreferences();
WebDriverManager.chromedriver().setup();
```

**Comment by vishalbiradar** [comment]
Below link will tell us about the right driver selection:
https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection

My chrome version is: Version 77.0.3865.75

By using the above version and hitting the below URL by removing the last two digits will give the driver version number suitable for the current chrome version.

https://chromedriver.storage.googleapis.com/LATEST_RELEASE_77.0.3865

With that received version number download the driver:
https://chromedriver.storage.googleapis.com/index.html?path=77.0.3865.40/

```
System.setProperty("webdriver.chrome.driver", "path/to/downloaded/driver");
ChromeOptions chromeOptions = new ChromeOptions();
```

**Comment by varletconst** [comment]
@amirated Your suggestion saved my day!

**Comment by appleyuchi** [comment]
> I got this working. Here are the steps:
> 
> I was getting this error:
> `selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 75`
> 
> I went to `chrome://settings/help` in my Google Chrome and found the version to be:
> `Version 77.0.3865.90 (Official Build) (64-bit)`
> 
> Then I went to: https://sites.google.com/a/chromium.org/chromedriver/downloads
> and downloaded the version for 77.
> Set the path of chromedriver in my code to the new downloaded chromedriver and it worked.

could you tell me how doyou set in your code?
Thanks

**Comment by ChirantanChatterjee** [comment]
See the browser version and update the driver accordingly. Like for example if your browser version is :
78.0.3904.108 
Then the driver 78.0.3904.105 should work just fine. 
I solved the issue like this.

**Comment by sangeethacg** [comment]
I have researched a lot and used many possible solutions mentioned in the various forums, none of them worked for me. I am trying to run this in CI/CD pipeline although able to run the protractor test cases in local and able to launch the browser but in CI/CD pipeline build it is failing below are the details the issue occurs for protractor 2.5.4 E/launcher - session not created: This version of ChromeDriver only supports Chrome version 79

i am using below postinstall under scripts in package.json

"postinstall": "npm uninstall -g webdriver-manager protractor && npm install -g webdriver-manager protractor && webdriver-manager update && cd ./node_modules/protractor && npm i webdriver-manager@latest",

"postinstall": "cd ./node_modules/protractor && npm i webdriver-manager@latest",

for the above script command below error is thrown I/file_manager - creating folder D:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium I/config_source - curl -oD:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium\chrome-response.xml https://chromedriver.storage.googleapis.com/ I/downloader - curl -oD:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium/chromedriver_79.0.3945.36.zip https://chromedriver.storage.googleapis.com/79.0.3945.16/chromedriver_win32.zip I/update - chromedriver: unzipping chromedriver_79.0.3945.36.zip I/launcher - Running 1 instances of WebDriver I/direct - Using ChromeDriver directly... E/launcher - session not created: This version of ChromeDriver only supports Chrome version 79

when i use below script command i get version issue for 76
postinstall": "webdriver-manager update"
I/update - chromedriver: file exists D:\a\1\s\node_modules\protractor\node_modules\webdriver-manager\selenium\chromedriver_76.0.3809.12.zip I/update - chromedriver: unzipping chromedriver_76.0.3809.12.zip I/update - chromedriver: chromedriver_76.0.3809.12.exe up to date I/launcher - Running 1 instances of WebDriver I/direct - Using ChromeDriver directly... E/launcher - session not created: This version of ChromeDriver only supports Chrome version 76 (Driver info: chromedriver=76.0.3809.12

below is config.json under webdriver-manager

{
"webdriverVersions": {
"selenium": "2.53.1",
"chromedriver": "2.27",
"maxChromedriver": "77",
"geckodriver": "v0.13.0",
"iedriver": "2.53.1",
"androidsdk": "24.4.1",
"appium": "1.6.5"
 },
 "cdnUrls": {
"selenium": "https://selenium-release.storage.googleapis.com/",
"chromedriver": "https://chromedriver.storage.googleapis.com/",
"geckodriver": "https://github.com/mozilla/geckodriver/releases/download/",
"iedriver": "https://selenium-release.storage.googleapis.com/",
"androidsdk": "http://dl.google.com/android/"
}
}
Tried many commands that might get worked on the pipeline build but none of them is helping me out. Can any one please suggest what could be the possible issue.

**Comment by ChirantanChatterjee** [comment]
I am not very sure with the above, but I used the prev stable release (78.0.3904.105 ) and it worked for me. Also for protector I usually use a simpler code like the below:

directConnect: true,
capabilities: {
  browserName: 'firefox',
  },

Also if possible please use selenium version 3.141

**Comment by Jyoti-d** [comment]
I have also tried to put WebDriverManager 3.6.1, dependency in pom file of my maven project, but still getting the same error with chrome only.  so plz i need hlep...... anyone plz solve this issue. Thank you

FAILED CONFIGURATION: @BeforeMethod setUp
**org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 81**
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DELL', ip: '192.168.0.111', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01145F73+2449267]
	Ordinal0 [0x01078361+1606497]
	Ordinal0 [0x00F6F969+522601]
	Ordinal0 [0x00F005F3+67059]
	Ordinal0 [0x00EFCD92+52626]
	Ordinal0 [0x00F1C127+180519]
	Ordinal0 [0x00F1BF2D+180013]
	Ordinal0 [0x00F19E5B+171611]
	Ordinal0 [0x00F01DD8+73176]
	Ordinal0 [0x00F02E50+77392]
	Ordinal0 [0x00F02DE9+77289]
	Ordinal0 [0x0108D8D7+1693911]
	GetHandleVerifier [0x011E4036+522726]
	GetHandleVerifier [0x011E3D74+522020]
	GetHandleVerifier [0x011F9187+609079]
	GetHandleVerifier [0x011E48A6+524886]
	Ordinal0 [0x01085CBC+1662140]
	Ordinal0 [0x0108F23B+1700411]
	Ordinal0 [0x0108F3A3+1700771]
	Ordinal0 [0x010A5215+1790485]
	BaseThreadInitThunk [0x7756919F+14]
	RtlInitializeExceptionChain [0x77DE0BBB+132]
	RtlInitializeExceptionChain [0x77DE0B91+90]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.qa.hubspot.base.BasePage.initialize_driver(BasePage.java:32)
	at com.qa.hubspot.tests.HomePageTest.setUp(HomePageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

SKIPPED CONFIGURATION: @AfterMethod tearDown
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod tearDown
SKIPPED CONFIGURATION: @BeforeMethod setUp
SKIPPED CONFIGURATION: @AfterMethod tearDown
SKIPPED: clickOnRepotsTest
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 81
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DELL', ip: '192.168.0.111', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01145F73+2449267]
	Ordinal0 [0x01078361+1606497]
	Ordinal0 [0x00F6F969+522601]
	Ordinal0 [0x00F005F3+67059]
	Ordinal0 [0x00EFCD92+52626]
	Ordinal0 [0x00F1C127+180519]
	Ordinal0 [0x00F1BF2D+180013]
	Ordinal0 [0x00F19E5B+171611]
	Ordinal0 [0x00F01DD8+73176]
	Ordinal0 [0x00F02E50+77392]
	Ordinal0 [0x00F02DE9+77289]
	Ordinal0 [0x0108D8D7+1693911]
	GetHandleVerifier [0x011E4036+522726]
	GetHandleVerifier [0x011E3D74+522020]
	GetHandleVerifier [0x011F9187+609079]
	GetHandleVerifier [0x011E48A6+524886]
	Ordinal0 [0x01085CBC+1662140]
	Ordinal0 [0x0108F23B+1700411]
	Ordinal0 [0x0108F3A3+1700771]
	Ordinal0 [0x010A5215+1790485]
	BaseThreadInitThunk [0x7756919F+14]
	RtlInitializeExceptionChain [0x77DE0BBB+132]
	RtlInitializeExceptionChain [0x77DE0B91+90]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.qa.hubspot.base.BasePage.initialize_driver(BasePage.java:32)
	at com.qa.hubspot.tests.HomePageTest.setUp(HomePageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

SKIPPED: verifyHomePageHeaderTest
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 81
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DELL', ip: '192.168.0.111', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01145F73+2449267]
	Ordinal0 [0x01078361+1606497]
	Ordinal0 [0x00F6F969+522601]
	Ordinal0 [0x00F005F3+67059]
	Ordinal0 [0x00EFCD92+52626]
	Ordinal0 [0x00F1C127+180519]
	Ordinal0 [0x00F1BF2D+180013]
	Ordinal0 [0x00F19E5B+171611]
	Ordinal0 [0x00F01DD8+73176]
	Ordinal0 [0x00F02E50+77392]
	Ordinal0 [0x00F02DE9+77289]
	Ordinal0 [0x0108D8D7+1693911]
	GetHandleVerifier [0x011E4036+522726]
	GetHandleVerifier [0x011E3D74+522020]
	GetHandleVerifier [0x011F9187+609079]
	GetHandleVerifier [0x011E48A6+524886]
	Ordinal0 [0x01085CBC+1662140]
	Ordinal0 [0x0108F23B+1700411]
	Ordinal0 [0x0108F3A3+1700771]
	Ordinal0 [0x010A5215+1790485]
	BaseThreadInitThunk [0x7756919F+14]
	RtlInitializeExceptionChain [0x77DE0BBB+132]
	RtlInitializeExceptionChain [0x77DE0B91+90]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.qa.hubspot.base.BasePage.initialize_driver(BasePage.java:32)
	at com.qa.hubspot.tests.HomePageTest.setUp(HomePageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

SKIPPED: verifyHomePageTitleTest
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 81
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'DELL', ip: '192.168.0.111', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_201'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x01145F73+2449267]
	Ordinal0 [0x01078361+1606497]
	Ordinal0 [0x00F6F969+522601]
	Ordinal0 [0x00F005F3+67059]
	Ordinal0 [0x00EFCD92+52626]
	Ordinal0 [0x00F1C127+180519]
	Ordinal0 [0x00F1BF2D+180013]
	Ordinal0 [0x00F19E5B+171611]
	Ordinal0 [0x00F01DD8+73176]
	Ordinal0 [0x00F02E50+77392]
	Ordinal0 [0x00F02DE9+77289]
	Ordinal0 [0x0108D8D7+1693911]
	GetHandleVerifier [0x011E4036+522726]
	GetHandleVerifier [0x011E3D74+522020]
	GetHandleVerifier [0x011F9187+609079]
	GetHandleVerifier [0x011E48A6+524886]
	Ordinal0 [0x01085CBC+1662140]
	Ordinal0 [0x0108F23B+1700411]
	Ordinal0 [0x0108F3A3+1700771]
	Ordinal0 [0x010A5215+1790485]
	BaseThreadInitThunk [0x7756919F+14]
	RtlInitializeExceptionChain [0x77DE0BBB+132]
	RtlInitializeExceptionChain [0x77DE0B91+90]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$errorHandler$0(W3CHandshakeResponse.java:62)
	at org.openqa.selenium.remote.HandshakeResponse.lambda$getResponseFunction$0(HandshakeResponse.java:30)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:126)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:128)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:74)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.qa.hubspot.base.BasePage.initialize_driver(BasePage.java:32)
	at com.qa.hubspot.tests.HomePageTest.setUp(HomePageTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)


===============================================
    Default test
    Tests run: 3, Failures: 0, Skips: 3
    Configuration Failures: 1, Skips: 5
===============================================


===============================================
Default suite
Total tests run: 3, Failures: 0, Skips: 3
Configuration Failures: 1, Skips: 5
===============================================

**Comment by sezginhmrc** [comment]
> I got this working. Here are the steps:
> 
> I was getting this error:
> `selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 75`
> 
> I went to `chrome://settings/help` in my Google Chrome and found the version to be:
> `Version 77.0.3865.90 (Official Build) (64-bit)`
> 
> Then I went to: https://sites.google.com/a/chromium.org/chromedriver/downloads
> and downloaded the version for 77.
> Set the path of chromedriver in my code to the new downloaded chromedriver and it worked.

**Comment by Palashio** [comment]
For some reason, my code runs and my google chrome opens but it wont download any of the pictures. Here's the code version I'm using. 

`from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import json
import os
import urllib
import argparse

#below is the search term you want to search on google images (first try out manually, which term fetches you more relevant images)
searchterm = 'red apples' 
url = "https://www.google.co.in/search?q="+searchterm+"&source=lnms&tbm=isch"

PROJECT_ROOT = os.path.abspath(os.path.dirname(__file__))
DRIVER_BIN = os.path.join(PROJECT_ROOT, "chromedriver")

browser = webdriver.Chrome(executable_path = DRIVER_BIN)
#browser = webdriver.Chrome()
browser.get(url)
header={'User-Agent':"Chrome/76.0.3809.36"}
counter = 0
succounter = 0

if not os.path.exists(searchterm):
    os.mkdir(searchterm)

for _ in range(500):
    browser.execute_script("window.scrollBy(0,10000)")

for x in browser.find_elements_by_xpath('//div[contains(@class,"rg_meta")]'):
    counter = counter + 1
    print("Total Count:", counter)
    print("Succsessful Count:", succounter)
    print("URL:",json.loads(x.get_attribute('innerHTML'))["ou"])
    img = json.loads(x.get_attribute('innerHTML'))["ou"]
    imgtype = json.loads(x.get_attribute('innerHTML'))["ity"]
    try:
        path = os.path.join(searchterm , searchterm + "_" + str(counter) + "." + imgtype)
        urllib.request.urlretrieve(img, path)
        succounter = succounter + 1
    except:
        print("can't get img")

print(succounter, "pictures succesfully downloaded")
browser.close()`

**Comment by Lockdown-SelfLearning** [comment]
Facing an error 
org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 83
Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
System info: host: 'DESKTOP-GOS2R28', ip: '192.168.0.109', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
Driver info: driver.version: ChromeDriver
remote stacktrace: Backtrace:
	Ordinal0 [0x00509563+2725219]
	Ordinal0 [0x00408551+1672529]
	Ordinal0 [0x002F0359+525145]
	Ordinal0 [0x00280B77+68471]
	Ordinal0 [0x0027D32C+54060]
	Ordinal0 [0x0029CC37+183351]
	Ordinal0 [0x0029CA3D+182845]
	Ordinal0 [0x0029A94B+174411]
	Ordinal0 [0x00282528+75048]
	Ordinal0 [0x002835A0+79264]
	Ordinal0 [0x00283539+79161]
	Ordinal0 [0x0041D607+1758727]
	GetHandleVerifier [0x00626546+1050150]
	GetHandleVerifier [0x00626291+1049457]
	GetHandleVerifier [0x006310D7+1094071]
	GetHandleVerifier [0x00626B46+1051686]
	Ordinal0 [0x00415B06+1727238]
	Ordinal0 [0x0041EB7B+1764219]
	Ordinal0 [0x0041ECE3+1764579]
	Ordinal0 [0x00434C05+1854469]
	BaseThreadInitThunk [0x75F16359+25]
	RtlGetAppContainerNamedObjectPath [0x778C7C24+228]
	RtlGetAppContainerNamedObjectPath [0x778C7BF4+180]

	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
	at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
	at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
	at com.lockdownlearning.SeleniumFirstJUnitTest.testgoogleDotCom(SeleniumFirstJUnitTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by OwynD** [comment]
> Facing an error
> org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 83
> Build info: version: '3.13.0', revision: '2f0d292', time: '2018-06-25T15:24:21.231Z'
> System info: host: 'DESKTOP-GOS2R28', ip: '192.168.0.109', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_251'
> Driver info: driver.version: ChromeDriver
> remote stacktrace: Backtrace:
> Ordinal0 [0x00509563+2725219]
> Ordinal0 [0x00408551+1672529]
> Ordinal0 [0x002F0359+525145]
> Ordinal0 [0x00280B77+68471]
> Ordinal0 [0x0027D32C+54060]
> Ordinal0 [0x0029CC37+183351]
> Ordinal0 [0x0029CA3D+182845]
> Ordinal0 [0x0029A94B+174411]
> Ordinal0 [0x00282528+75048]
> Ordinal0 [0x002835A0+79264]
> Ordinal0 [0x00283539+79161]
> Ordinal0 [0x0041D607+1758727]
> GetHandleVerifier [0x00626546+1050150]
> GetHandleVerifier [0x00626291+1049457]
> GetHandleVerifier [0x006310D7+1094071]
> GetHandleVerifier [0x00626B46+1051686]
> Ordinal0 [0x00415B06+1727238]
> Ordinal0 [0x0041EB7B+1764219]
> Ordinal0 [0x0041ECE3+1764579]
> Ordinal0 [0x00434C05+1854469]
> BaseThreadInitThunk [0x75F16359+25]
> RtlGetAppContainerNamedObjectPath [0x778C7C24+228]
> RtlGetAppContainerNamedObjectPath [0x778C7BF4+180]
> 
> ```
> at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> at java.lang.reflect.Constructor.newInstance(Unknown Source)
> at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$new$0(W3CHandshakeResponse.java:57)
> at org.openqa.selenium.remote.W3CHandshakeResponse.lambda$getResponseFunction$2(W3CHandshakeResponse.java:104)
> at org.openqa.selenium.remote.ProtocolHandshake.lambda$createSession$0(ProtocolHandshake.java:123)
> at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
> at java.util.Spliterators$ArraySpliterator.tryAdvance(Unknown Source)
> at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
> at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
> at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
> at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
> at java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
> at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
> at java.util.stream.ReferencePipeline.findFirst(Unknown Source)
> at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:126)
> at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:73)
> at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:136)
> at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
> at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:548)
> at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:212)
> at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
> at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
> at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
> at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:123)
> at com.lockdownlearning.SeleniumFirstJUnitTest.testgoogleDotCom(SeleniumFirstJUnitTest.java:23)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> at java.lang.reflect.Method.invoke(Unknown Source)
> at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
> at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
> at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
> ```

I am also receiving this error intermittently but only in jenkins during nightly runs

**Comment by Nivedh-prog** [comment]
> Below link will tell us about the right driver selection:
> https://sites.google.com/a/chromium.org/chromedriver/downloads/version-selection
> 
> My chrome version is: Version 77.0.3865.75
> 
> By using the above version and hitting the below URL by removing the last two digits will give the driver version number suitable for the current chrome version.
> 
> https://chromedriver.storage.googleapis.com/LATEST_RELEASE_77.0.3865
> 
> With that received version number download the driver:
> https://chromedriver.storage.googleapis.com/index.html?path=77.0.3865.40/
> 
> ```
> System.setProperty("webdriver.chrome.driver", "path/to/downloaded/driver");
> ChromeOptions chromeOptions = new ChromeOptions();
> ```

thank u so much,u saved my day

**Comment by pushpraj4131** [comment]
> I got this working. Here are the steps:
> 
> I was getting this error:
> `selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 75`
> 
> I went to `chrome://settings/help` in my Google Chrome and found the version to be:
> `Version 77.0.3865.90 (Official Build) (64-bit)`
> 
> Then I went to: https://sites.google.com/a/chromium.org/chromedriver/downloads
> and downloaded the version for 77.
> Set the path of chromedriver in my code to the new downloaded chromedriver and it worked.

I am unable to set path. Can you please help me a little more in setting path ?

**Comment by jgephart** [comment]
@pushpraj4131 try opening up your package.json and just changing your chromedriver version to match your current chrome version.

For me I went from:
"chromedriver": "^83.0.0",
to
"chromedriver": "^85.0.0",

I did a "yarn install" and the tests started working again. Good luck!

**Comment by melorillaGH** [comment]
> @pushpraj4131 try opening up your package.json and just changing your chromedriver version to match your current chrome version.
> 
> For me I went from:
> "chromedriver": "^83.0.0",
> to
> "chromedriver": "^85.0.0",
> 
> I did a "yarn install" and the tests started working again. Good luck!

This solved my issue. thanks!

**Comment by jgephart** [comment]
> This solved my issue. thanks!

Awesome! Glad to hear it! :D

**Comment by coddiction** [comment]
**Best way to solve this problem for mac**
For mac users, this is the best way to solve,
Download the chromedriver (after checking the current version of your chrome browser from `about chrome`)
and then paste that chromedriver in this directory

   ` /usr/local/bin`

If this directory is not found to you then from finder 
click on go 
then select computer
then press `command+shift+.` (this shows the hidden files in mac)
then definitely you will see these directory easily

HaPpY Coding 😇

**Comment by verifiedanswer** [comment]
[[Solved] selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 104 Current browser version is 106](https://verifiedanswer.com/selenium-common-exceptions-sessionnotcreatedexception-message-session-not-created-this-version-of-chromedriver-only-supports-chrome-version-104-current-browser-version-is-106/)

**Comment by mohanaravindvarma** [comment]
java.lang.ExceptionInInitializerError
Caused by: io.github.bonigarcia.wdm.config.WebDriverManagerException: java.lang.NumberFormatException: For input string: "public"
Caused by: java.lang.NumberFormatException: For input string: "public"

May i know please know why this error is coming and what can i do to resolve it? its only failing in pipeline not in my local machine.
