### ISSUE TITLE
Timed out receiving message from renderer: 0.100

### ISSUE THREAD

**Issue by etuviana** [bonigarcia/webdrivermanager#442]
In LOG i see this problems 

Starting ChromeDriver 80.0.3987.106 (f68069574609230cf9b635cd784cfb1bf81bb53a-refs/branch-heads/3987@{#882}) on port 13864
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
Feb 25, 2020 5:00:45 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: W3C
**[1582678866.122][SEVERE]: Timed out receiving message from renderer: 0.100
[1582678866.324][SEVERE]: Timed out receiving message from renderer: 0.100
[1582678866.514][SEVERE]: Timed out receiving message from renderer: 0.100
[1582678866.619][SEVERE]: Timed out receiving message from renderer: 0.100
[1582678866.726][SEVERE]: Timed out receiving message from renderer: 0.100**

Browser: Run on Google Chrome is up to date
Version 80.0.3987.122 (Official Build) (64-bit)

OS: Windows 10 (64-bit)

POM: 

WebDriverManager version 3.7.1

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>3.7.1</version>
		</dependency>

In JAVA code

case "Chrome":
			WebDriverManager.chromedriver().setup(); 

what the problems ?

Thanks

**Comment by Longtrainz** [comment]
Same error: getting same messages and then test crashes after approx, 1 minute of running:

`org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: -0.007
  (Session info: chrome=80.0.3987.122)
Build info: version: '4.0.0-alpha-4', revision: 'c2d955b49e'
System info: host: 'ODS1-LHP-F51105', ip: '172.17.131.4', os.name: 'Windows 10', os.arch: 'x86', os.version: '10.0', java.version: '1.8.0_231'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 80.0.3987.122, chrome: {chromedriverVersion: 80.0.3987.106 (f68069574609..., userDataDir: C:\Users\VLADYS~1.BUK\AppDa...}, goog:chromeOptions: {debuggerAddress: localhost:59686}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: d8a8ba136850a7da3efd84c647d646ff`

**Comment by etuviana** [comment]
still wait to solution

**Comment by Longtrainz** [comment]
Same issue.

**Comment by anuragdeshpande** [comment]
same issue here.

**Comment by saranyas72** [comment]
same issue, please fix it.

**Comment by etuviana** [comment]
**That's what I found Known issue, due to chrome update**

temporary solution
Either download a browser version Or wait for Chrome to be repaired


https://stackoverflow.com/questions/60114639/timed-out-receiving-message-from-renderer-0-100-log-messages-using-chromedriver

https://support.google.com/chrome/thread/25685640?hl=en

**Comment by bonigarcia** [comment]
These traces are written by chromedriver, and therefore, this is not actually an issue of WebDrivermanager. I suppose it will be fixed in future releases of chromedriver. You can check more info [here](https://bugs.chromium.org/p/chromedriver/issues/list?q=Timed%20out%20receiving%20message%20from%20renderer&can=2).

**Comment by khairess** [comment]
same issue in my code also.

**Comment by tipsey** [comment]
Chrome Browser:  Version 81.0.4044.129
Chrome Selenium Driver - 32 bti 81.0.444.6900

Still getting timed out receiving message from renderer
Tried setting Page Load Strategy to None but this will not execute tests well.

**Comment by loyd0729** [comment]
Hi All, 
You might want to watch this video. Mr. Otwani demonstrate how to fix or supress the warning message. 
https://www.youtube.com/watch?v=C8GuQViFD3Y&t=379s

**Comment by etuviana** [comment]
@loyd0729  Hi , its not fix the issue just a hiding.

**Comment by ShahbaazShah1990** [comment]
People who cannot access Youtube(due to policies etc..) to watch the above link provided by @loyd0729,


Add this line -> **System.setProperty("webdriver.chrome.silentOutput", "true");**
System.setProperty("webdriver.chrome.driver", System.getProperty("user.dir") + "/dependencies/chromedriver.exe");

Note : as @etuviana Mentioned its not a fix this just hides it

> @loyd0729 Hi , its not fix the issue just a hiding.

**Comment by umadb27** [comment]
Yeah adding the line System.setProperty("webdriver.chrome.silentOutput", "true"); just hides the timeout log.The issue is not fixed by adding the line.
What is the solution for the problem.Please help.None of my tests are running

**Comment by umadb27** [comment]
This issue started when my chrome version is updated to 80.0.I installed chrome 81.Still same issue.
In which version of chrome this issue is fixed

**Comment by loyd0729** [comment]
Hi all, 
I've been looking around what's really causing this message but I keep getting different answers and solution. Some are saying it's not really an issue at least for us it's not an issue. It seems this happens with 80 and 81 release, this issue should be fixed with 82 release per https://stackoverflow.com/questions/60114639/timed-out-receiving-message-from-renderer-0-100-log-messages-using-chromedriver. As of now https://chromedriver.chromium.org/ skipped 82 release but release 83 (Current Stable release). I was also looking for release notes but no avail. If anyone gets a chance testing 83 release and let us know what are your findings. I'll definitely try downloading it later and test it tonight. Thanks!

**Comment by aryanaarya299** [comment]
// Use this line of code keep the code first statement System.setProperty(ChromeDriverService.CHROME_DRIVER_SILENT_OUTPUT_PROPERTY, "true");

**Comment by MichaelDally** [comment]
> // Use this line of code keep the code first statement System.setProperty(ChromeDriverService.CHROME_DRIVER_SILENT_OUTPUT_PROPERTY, "true");

This doesn't fix the problem, it only hides it.

**Comment by larisa31grecu** [comment]
Any updates in regards to that? I am using chrome driver version 84 and this issue is still present

**Comment by keuninkske** [comment]
same problem here, windows server2012, chrome 84 and code written in python3.7

return i get:
`
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 600.000
  (Session info: chrome=84.0.4147.125)
`

**Comment by IonutG24** [comment]
I had set driver.manage().timeouts().pageLoadTimeout(10, TimeUnit.SECONDS) (10 seconds) right in the beginning of the test. If a page did not load in 10 seconds I got  Timed out receiving message from renderer: 10

So just remove pageLoadTime out or set it to wait more seconds.

**Comment by larisa31grecu** [comment]
@IonutG24  I have set driver.manage().timeouts().pageLoadTimeout to 120 seconds it still fails randomly, so this is not a solution, at least not for me. I have been running today a suite of tests, and one of them failed with the error: 'Timed out receiving message from renderer: 28.751 (Session info: chrome=85.0.4183.102)'

**Comment by SebastanBucki07** [comment]
I have the same issue, locally always test passed, but on Jenkins random error
`Failed: timeout: Timed out receiving message from renderer: 5.000   (Session info: headless chrome=85.0.4183.121) Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53' System info: host: 'DESKTOP-0QRUEFH'`

I've tried everything what I found in google :( 

`'chromeOptions': {
            args: [
                '--start-maximized',
                '--disable-blink-features="BlockCredentialedSubresources"',
                '--dns-prefetch-disable',
                'enable-automation',
                '--disable-extensions',
                '--disable-dev-shm-usage',
                '--aggressive-cache-discard',
                '--disable-cache',
                '--disable-application-cache',
                '--disable-offline-load-stale-cache',
                '--disk-cache-size=0',
                '--disable-browser-side-navigation',
                '--dns-prefetch-disable',
                '--disable-gpu',
                '--silent',
                '--no-sandbox',
                '--force-device-scale-factor=1',
                '--headless',
                'user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36',
                'enable-features=NetworkServiceInProcess',
                '--window-size=1920,1080'
            ],`

` framework: 'jasmine',

    allScriptsTimeout: 400000,
    getPageTimeout: 110000,

    // Options to be passed to Jasmine.
    jasmineNodeOpts: {
        defaultTimeoutInterval: 360000
    },
`

**Comment by vinothkumarnk** [comment]
While fixing my firefox run through Jenkins, Chrome also worked after the following:
Change the registry key of the machine - 
HKLM\SYSTEM\CurrentControlSet\Control\Windows\NoInteractiveServices to 0

**Comment by armanit93** [comment]
Still facing this problem in 2022. Did anyone find a solution for this?
